name: Deploy docs on pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packet manager
        run: npm i pnpm -g

      - name: Install dependencies
        run: pnpm install --dangerously-allow-all-builds

      - name: Build application
        run: pnpm run build

      - name: Add CNAME
        run: echo "wiki.minecis.net" > ./doc_build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc_build
          publish_branch: gh-pages
          destination_dir: .
          allow_empty_commit: true
