name: Deploy docs on pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Add CNAME
        run: echo "wiki.minecis.net" > ./.vitepress/dist/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vitepress/dist
          publish_branch: gh-pages
          destination_dir: .
          allow_empty_commit: true
