name: Build and deploy docs

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: kartoshkayty/MCNET-Docs
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Use Node.js v24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.vitepress/dist
